version: '3.7'

services:
  app:
    container_name: dockerized-react-app
    image: fastfeet_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/web
    command: bash -c 'yarn && yarn start'
    stdin_open: true
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on: [backend]
  backend:
    container_name: dockerized-node-app
    image: fastfeet_app
    working_dir: /app/backend
    command: bash -c 'yarn && yarn dev'
    stdin_open: true
    ports:
      - '3333:3333'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development
    depends_on: [db]
  db:
    image: postgres:latest
    volumes:
      - './backend/db:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  db_seeding:
    container_name: db-seeding
    image: fastfeet_app
    working_dir: /app/backend
    command: bash -c 'yarn && yarn sequelize db:create && yarn sequelize db:migrate && yarn sequelize db:seed:all'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development
    depends_on: [db]

